global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'storage-nodes'
    static_configs:
      - targets:
        - 'storage-node-1:8081'
        - 'storage-node-2:8082'
        - 'storage-node-3:8083'
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
