global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cluster-coordinator'
    static_configs:
      - targets: ['cluster-coordinator:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'log-producer'
    static_configs:
      - targets: ['log-producer:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'log-consumer'
    static_configs:
      - targets: ['log-consumer:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
