global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'state-producer'
    static_configs:
      - targets: ['state-producer:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'state-consumer'
    static_configs:
      - targets: ['state-consumer:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'state-query-api'
    static_configs:
      - targets: ['state-query-api:8083']
    metrics_path: '/actuator/prometheus'
