global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'query-coordinator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['query-coordinator:8080']

  - job_name: 'partition-node-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['partition-node-1:8081']

  - job_name: 'partition-node-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['partition-node-2:8082']

  - job_name: 'partition-node-3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['partition-node-3:8083']
