global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'log-producer'
    static_configs:
      - targets: ['log-producer:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'faceted-search-service'
    static_configs:
      - targets: ['faceted-search-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'aggregation-service'
    static_configs:
      - targets: ['aggregation-service:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
