global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'event-producer'
    static_configs:
      - targets: ['event-producer:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'session-processor'
    static_configs:
      - targets: ['session-processor:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'session-analytics'
    static_configs:
      - targets: ['session-analytics:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
