global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'log-producer'
    static_configs:
      - targets: ['log-producer:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'indexing-service'
    static_configs:
      - targets: ['indexing-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'search-api'
    static_configs:
      - targets: ['search-api:8083']
    metrics_path: '/actuator/prometheus'
