global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'log-producer'
    static_configs:
      - targets: ['log-producer:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'critical-consumer'
    static_configs:
      - targets: ['critical-consumer:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'normal-consumer'
    static_configs:
      - targets: ['normal-consumer:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'escalation-service'
    static_configs:
      - targets: ['escalation-service:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
