global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'encryption-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['encryption-service:8081']
  
  - job_name: 'log-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['log-producer:8080']
  
  - job_name: 'log-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['log-consumer:8082']
  
  - job_name: 'query-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['query-service:8083']
