global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'application-log-shipper'
    static_configs:
      - targets: ['application-log-shipper:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'infrastructure-log-shipper'
    static_configs:
      - targets: ['infrastructure-log-shipper:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'transaction-log-shipper'
    static_configs:
      - targets: ['transaction-log-shipper:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'log-gateway'
    static_configs:
      - targets: ['log-gateway:8080']
    metrics_path: '/actuator/prometheus'
